### ISSUE TITLE
-fPIC error when compiling with gcc 7.2.0

### ISSUE THREAD

**Issue by wesm** [conda-forge/gflags-feedstock#11]
I encountered this when testing a Dockerized build on Arch Linux with gcc 7.2.0

```
/usr/sbin/ld: /home/root/toolchain/lib/libgflags.a(gflags.cc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/sbin/ld: /home/root/toolchain/lib/libgflags.a(gflags_reporting.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/sbin/ld: /home/root/toolchain/lib/libgflags.a(gflags_completions.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
CMakeFiles/json-integration-test.dir/json-integration-test.cc.o: In function `__static_initialization_and_destruction_0(int, int)':
/home/root/arrow/cpp/src/arrow/ipc/json-integration-test.cc:42: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/home/root/arrow/cpp/src/arrow/ipc/json-integration-test.cc:43: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/home/root/arrow/cpp/src/arrow/ipc/json-integration-test.cc:44: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/usr/sbin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

We've been statically linking this gflags elsewhere without issues, so I'm not totally sure what's up. There might be some other gcc7 issues to sort out here

Here is the Dockerfile for this

https://gist.github.com/wesm/1e1f05868f94521950e623d29d40f2c6

**Comment by wesm** [comment]
This was a red herring due to gtest being compiled with the gcc5 ABI enabled

**Comment by alendit** [comment]
I'm having the same problem. I'm not quite sure how you solved it.
